spring.application.name=biblioteca

#H2
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.datasource.username=sa
spring.datasource.password=



springdoc.api-docs.info.title=Minha API Incrível
springdoc.api-docs.info.description=Documentação dos serviços da minha aplicação.
springdoc.api-docs.info.version=v1.0.0